//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webbapplikation.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GustavsObjektdatabasEntities : DbContext
    {
        public GustavsObjektdatabasEntities()
            : base("name=GustavsObjektdatabasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Länder> Länder { get; set; }
        public DbSet<Modeller> Modeller { get; set; }
        public DbSet<Märken> Märken { get; set; }
        public DbSet<Städer> Städer { get; set; }
    }
}
