//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webbapplikation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Länder
    {
        public Länder()
        {
            this.Städer = new HashSet<Städer>();
        }
    
        public int id { get; set; }
        public string namn { get; set; }
        public int språkid { get; set; }
        public int namnspråkid { get; set; }
    
        public virtual ICollection<Städer> Städer { get; set; }
    }
}
