//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webbapplikation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modeller
    {
        public int id { get; set; }
        public string namn { get; set; }
        public string konfig { get; set; }
        public int volym { get; set; }
        public string kaross { get; set; }
        public int cyl { get; set; }
        public int startår { get; set; }
        public Nullable<int> slutår { get; set; }
        public int märkeid { get; set; }
        public string beskrivning { get; set; }
    
        public virtual Märken Märken { get; set; }
    }
}
